### ISSUE TITLE
ABError: Sequence 'ERR' was not found in the name or count file

### ISSUE THREAD

**Issue by ne1al** [mothur/mothur#693] opened 2019-12-31 11:42 UTC
Hello,
I am using mothur for analyzing a public available data set with single end layout. While `cluster`, I had the following error: `ABError: Sequence 'ERR' was not found in the name or count file. Please correct`. Could you please help? I tried both commands for cluster:
`mothur > cluster(column=sel_normal.merged.filtered.good.unique.filter.precluster.pick.dist, name=sel_normal.merged.filtered.good.names, cutoff=0.03)`

`mothur > cluster(column=sel_normal.merged.filtered.good.unique.filter.precluster.pick.dist, count=sel_normal.merged.filtered.good.unique.filter.precluster.pick.count_table, cutoff=0.03)`

The workflow I followed (after filtering the reads with fastp) was:
```
screen.seqs
unique.seqs
count.seqs
align.seqs
filter.seqs
pre.cluster
chimera.vsearch
remove.seqs
dist.seqs
```

**Comment by mothur-westcott** [comment] 2020-01-06 13:42
Could you post your complete log file?

**Comment by ne1al** [comment] 2020-01-12 15:13
@mothur-westcott the complete log is separated into two files attached here:
[mothur.1577525825.logfile1.txt](https://github.com/mothur/mothur/files/4050762/mothur.1577525825.logfile1.txt)
[mothur.1577865565.logfile2.txt](https://github.com/mothur/mothur/files/4050764/mothur.1577865565.logfile2.txt)

**Comment by mothur-westcott** [comment] 2020-01-13 16:03
Thanks for sending your log files. I am not seeing anything jumping out at me as the cause. Could you post your count file so I can take a closer look?

Also, a few things to consider:

1. I can see you are merging fasta files into a large fasta file for your whole dataset. Are these files from different samples? Are you interested in comparing the samples? If so, I recommend using the make.group command to assign the reads in each *.filtered.fasta file to a sample name. Here's how:

   mothur > make.group(fasta=ERR1597020.filtered.fasta-ERR1678393.filtered.fasta-ERR1678364.filtered.fasta-ERR2033405.filtered.fasta...ERR2033281.filtered.fasta, groups= ERR1597020-ERR1678393-ERR1678364-ERR2033405... ERR2033281, output=sel_normal.merged.filtered.groups)

2. With this group file, you can create a count file that includes the sample counts for each sequence.

  mothur > make.table(group=sel_normal.merged.filtered.groups, name=sel_normal.merged.filtered.good.names)

3. We recommend running the screen.seqs command after aligning to ensure good overlap. The command below indicates that all "good" sequences must start by 13862 and end after 21774.

  mothur > screen.seqs(fasta=sel_normal.merged.filtered.good.unique.align, count=sel_normal.merged.filtered.good.count_table, start=13862, end= 21774) 

4. If you are interested in the sample data. We recommend running chimera.vsearch with dereplicate=t. The dereplicate parameter allows you to remove chimeras from individual samples rather than the whole dataset. 

5. You have a large distance matrix. "It took 34482 secs to find distances for 405975 sequences. 3394165335 distances below cutoff 0.03." Nearly 3.4 billion distances. Do you have enough RAM to complete the clustering?

**Comment by ne1al** [comment] 2020-01-15 12:28
Thank you so much @mothur-westcott  for your very comprehensive reply!
1. Yes, I am comparing samples. So, I should be making groups instead.
2. I think I did **not** get the same start by 13862 and end after 21774 while I was checking summary tables. I get ## instead. May be the sequences themselves are not of enough coverage? What do you think?
3. For the distance matrix, is there any way to decrease it? Why would it be that large in the first place? Does it depend on the number of reads I have in each fasta file separately?

**Comment by mothur-westcott** [comment] 2020-01-15 16:30
1. Great, this should also improve mothur's processing time since many commands are parallelized to process multiple samples at the same time.

2. I was looking at the summary table after aligning. 

mothur > summary.seqs(fasta=sel_normal.merged.filtered.good.unique.align, count=sel_normal.merged.filtered.good.count_table)

Using 32 processors.

		Start	End	NBases	Ambigs	Polymer	NumSeqs
Minimum:	0	0	0	0	1	1
2.5%-tile:	13862	21774	150	0	3	46605
25%-tile:	13862	21776	150	0	4	466041
Median: 	13862	21776	150	0	4	932081
75%-tile:	13862	21777	150	0	5	1398121
97.5%-tile:	13862	21780	151	0	6	1817557
Maximum:	43116	43116	151	0	8	1864160
Mean:	13956	21780	148	0	4
# of unique seqs:	574170
total # of seqs:	1864160

It took 150 secs to summarize 1864160 sequences.

Output File Names:
sel_normal.merged.filtered.good.unique.summary

The start and end parameters help to ensure good overlap in your reads, which reduces spurious OTUs. The start parameter is used to set a position the "good" sequences must start by. The end parameter is used to set a position the "good" position sequences must end after. From the table above, we can see that 97.5% of your reads start by 13862. Looking at the end values, we can see that 97.5% of your reads end after 21774.

3. Pat's written a blog about large distance matrices, http://blog.mothur.org/2014/09/11/Why-such-a-large-distance-matrix/, you may find helpful.

**Comment by ne1al** [comment] 2020-01-15 19:22
@mothur-westcott   Your answers have been very helpful for me! I will consider each point you mentioned in my future analyses because unfortunately I don't have access to the above data files anymore. Thank you so much Sarah!

**Closed** 2020-01-27 16:24 UTC
Labels: Support
