### ISSUE TITLE
collect.shared fails on shared files containing more than one label

### ISSUE THREAD

**Issue by shiltemann** [mothur/mothur#497] opened 2018-07-27 17:23 UTC
release: 1.40.5

When I run a `collect.shared` command on a shared file containing more than one level (0.03 etc) I get the following error:

```
mothur > collect.shared(shared=amazon.an.shared)
[ERROR]: requesting groups not present in files, aborting.
```

link to dataset: [amazon.an.shared](https://github.com/galaxyproject/tools-iuc/blob/master/tools/mothur/test-data/amazon.an.shared) 

If I remove all but one level from the file, it completes without a problem. This command ran successfully on this dataset in version 1.39.5.

I have noticed this error in several other commands that take shared files as input as well. (e.g. cooccurrence, corr.axes, dist.shared, filter.shared, get.groups, get.otulabels, ..)

**Comment by mothur-westcott** [comment] 2018-08-02 14:18
Thanks for reporting this issue. The problem is caused by the header line being printed after each distance in the shared file. This is throwing off downstream commands.  The shared file created looks like:

label	numOtus	Otu01	Otu02	Otu03	Otu04	Otu05	Otu06	Otu07	Otu08	Otu09	Otu10 ... 
1	49	GQY1XT001A03YW,GQY1XT001A0BQS,GQY1XT001A0L0R,GQY1XT001A0UZX,GQY1XT001A0VZD,GQY1XT001A0YTE,GQY1XT001A103Z,...
label	numOtus	Otu01	Otu02	Otu03	Otu04	Otu05	Otu06	Otu07	Otu08	Otu09	Otu10...
2	49	GQY1XT001A03YW,GQY1XT001A0BQS,GQY1XT001A0L0R,GQY1XT001A0UZX,GQY1XT001A0VZD,GQY1XT001A0YTE,GQY1XT001A103Z,GQY1XT001A15A7,...
...

This will be resolved in our next release. In the meantime you can workaround the issue by deleting the extra OTU label lines. Sorry for the inconvenience.

**Comment by shiltemann** [comment] 2018-08-03 07:17
thanks @mothur-westcott :+1:

**Closed** 2018-09-06 18:00 UTC
Labels: Bugs, Priority
