### ISSUE TITLE
no *good.groups file produced with screen.seqs

### ISSUE THREAD

**Issue by mmuscarella** [mothur/mothur#476] opened 2018-06-14 03:23 UTC
Recently updated mothur:
```Linux 64Bit Version
Mothur version=1.40.4
Release Date=05/31/2018```

There seems to be an issue with screen.seqs not producing a `*.good.groups` file. 
```mothur > screen.seqs(fasta=HMWF.trim.contigs.fasta, group=HMWF.contigs.groups, summary=HMWF.trim.contigs.summary, maxambig=0, maxlength=275, processors=8)
...
It took 72 secs to screen 7956282 sequences, removed 1381800.

Output File Names: 
HMWF.trim.contigs.good.summary
HMWF.trim.contigs.good.fasta
HMWF.trim.contigs.bad.accnos
```
There should have been a `*.good.groups` file produced right? This is currently causing downstream issues.

**Comment by mmuscarella** [comment] 2018-06-14 03:38
**Temp Fix**:
```remove.seqs(accnos=HMWF.trim.contigs.bad.accnos, group=HMWF.contigs.groups)
Removed 1381800 sequences from your group file.

Output File Names: 
HMWF.contigs.pick.groups```

**Comment by Shellfishgene** [comment] 2018-06-14 11:32
I guess this is the same bug: The ```screen.seqs``` command also does not produce a new count file if given one. Also version 1.40.4.

**Comment by mothur-westcott** [comment] 2018-06-14 13:36
Thanks for reporting this issue. It looks like the screen.seqs command is not creating the new group or count files. This will be fixed on our next release. In the meantime, you can use the *bad.accnos file to remove the bad reads from the group or count file manually.  To do so insert a remove.seqs command after each screen.seqs command.  

mothur > remove.seqs(accnos=current, count=current) 

or 

mothur > remove.seqs(accnos=current, group=current)

Sorry for the inconvenience.

**Comment by mmuscarella** [comment] 2018-06-14 14:48
Note to anyone using this temp fix: remove.seqs produces `*.pick.groups` so if you manually write out the names you will either need to change your batch file or change the name of the group file with a system command.

**Comment by wenzel-sylvester** [comment] 2018-06-18 10:22
@mothur-westcott thank you for your help with the workaround. Had the same problem and just didn't know what to do.
When will the next release, with the fixed screen.seqs command be available?

Right now I'm having an issue with the following step after the workaround:
summary.seqs(count=stability.trim.contigs.good.count_table)

I'm getting the error: 
[ERROR]: 'M05074_86_000000000-D46N2_1_1101_18840_14135' is not in your name or count file, please correct.
[ERROR]: Your count file contains 31930 unique sequences, but your fasta file contains 1. File mismatch detected, quitting command.

Can that be caused by the workaround or what could be the reason for that error?

**Comment by mothur-westcott** [comment] 2018-06-19 18:15
Can you try our latest version, https://github.com/mothur/mothur/releases/tag/v1.40.5?

**Comment by w-sylvester** [comment] 2018-06-21 09:21
@mothur-westcott just tried it and it seems to be working. I get a good.groups file as output from the screen.seqs command.
Thank you for the quick fix!

**Closed** 2018-06-21 13:22 UTC
Labels: Bugs, Command:Screen.seqs

**Comment by mvcarlosdominguez** [comment] 2018-06-29 16:01
@mothur-westcott , I'm working with Galaxy and the "screen.seqs" doesn't have the version 1.40.5 and a im having the same problem.

Could you help me?

Thanks

**Comment by penacort** [comment] 2018-07-05 02:04
I have been trying to process my sequences using the mothur v.1.40.5 but when running command "summary.seqs" is taking ages. I used previous versions as 1.35 and 1.39 and I am sure that never took so much time.

Is there any problem ?

I am using the same computer that I used previously (MacBook Pro, 3.1 GHz Intel Core i7, 16 GB 1867 MHz DDR3). I updated the OS to 10.13 since was required to run this version of mothur. I have 96 samples, with a total of 16.7 GB and as an example I am attaching one run of summary.seqs, after running "unique.seqs"

x. eg. 

mothur > summary.seqs(count=stability.trim.contigs.good.count_table)
Using stability.trim.contigs.good.unique.fasta as input file for the fasta parameter.

Using 4 processors.

		Start	End	NBases	Ambigs	Polymer	NumSeqs
Minimum:	1	250	250	0	2	1
2.5%-tile:	1	308	308	0	4	322277
25%-tile:	1	426	426	0	6	3222764
Median: 	1	446	446	0	13	6445528
75%-tile:	1	459	459	0	15	9668292
97.5%-tile:	1	474	474	0	22	12568779
Maximum:	1	500	500	0	251	12891055
Mean:	1	431	431	0	12
# of unique seqs:	11368825
total # of seqs:	12891055

It took 8101 secs to summarize 12891055 sequences.

Output File Names:
 stability.trim.contigs.good.unique.summary

It took almost 2.5 hours to run 

Just now I am running the same command after having run "align.seqs" and has been running it for almost 10 hours and hasn't finish yet.

I will really appreciate your help

Thanks

**Comment by mothur-westcott** [comment] 2018-07-05 12:39
Hmm... that seems like a very long time.  In version 1.40 we updated mothur's threaded code.  This change would impact the summary.seqs command, and includes shared memory and shared writing instead of merging summary files after processing. Could you be running out of RAM?

**Comment by penacort** [comment] 2018-07-05 12:55
I have 16GB of ram, it used to be more than enough previously. It seems that only 6 gb have been used and still so slow

Luis Carlos Peña Cortes
DVM. MSc. PhD
Profesor Asociado
Facultad de Ciencias Agrarias
Universidad de Pamplona



On Jul 5, 2018, at 8:39 AM, Sarah Westcott <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm... that seems like a very long time. In version 1.40 we updated mothur's threaded code. This change would impact the summary.seqs command, and includes shared memory and shared writing instead of merging summary files after processing. Could you be running out of RAM?

**Comment by penacort** [comment] 2018-07-18 14:05
Hi Dr Westcott:

I am still having problems running my sequences. I verified the memory use of my computer and it is using from 32% to 50%. I even clean the HDD from files and it has almost 50% or more of free space.

I am processing the sequences again and it has stop in this step (image attached) since 24 h ago
<img width="1126" alt="screen shot 2018-07-17 at 5 46 49 pm" src="https://user-images.githubusercontent.com/13107087/42886552-d8eaf20e-8a71-11e8-92c2-8e6a0ade0c1b.png">

As I mentioned, I tried using different versions of your software and even using different versions of silva align files as well as creating a customize sequences for v4 as suggested in MiSeq SOP by using PCR.SEQS.

I really don't know what to do. Can you give me any idea, please.

**Comment by pschloss** [comment] 2018-08-13 13:33
The output from summary.seqs makes it clear that this region is much larger than the v4 region, which is 250 nt. Your contigs are about 450 nt long. This would cause data quality issues with the curation pipeline as described in http://blog.mothur.org/2014/09/11/Why-such-a-large-distance-matrix/

Also, your screen grab makes me think that you had a bad sequencing run. It crashes out around 100 nt into the second read. I'd start asking questions about the version of the chemistry that was used, the % PhiX, and clustering density.
